I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 20, in script
    d "True Dragon!"
  File "renpy/common/00action_control.rpy", line 131, in __call__
    renpy.show_screen(self.screen, *self.args, **self.kwargs)
Exception: Screen global_map is not known.


-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 20, in script
    d "True Dragon!"
  File "/home/zloysnegovik/files/renpy/renpy-8.3.6-sdk/renpy/ast.py", line 2586, in execute
    Say.execute(self)
  File "/home/zloysnegovik/files/renpy/renpy-8.3.6-sdk/renpy/ast.py", line 623, in execute
    renpy.exports.say(who, what, *args, **kwargs)
  File "/home/zloysnegovik/files/renpy/renpy-8.3.6-sdk/renpy/exports/sayexports.py", line 132, in say
    who(what, *args, **kwargs)
  File "/home/zloysnegovik/files/renpy/renpy-8.3.6-sdk/renpy/character.py", line 1470, in __call__
    self.do_display(who, what, cb_args=self.cb_args, dtt=dtt, **display_args)
  File "/home/zloysnegovik/files/renpy/renpy-8.3.6-sdk/renpy/character.py", line 1117, in do_display
    display_say(who,
  File "/home/zloysnegovik/files/renpy/renpy-8.3.6-sdk/renpy/character.py", line 814, in display_say
    rv = renpy.ui.interact(mouse='say', type=type, roll_forward=roll_forward)
  File "/home/zloysnegovik/files/renpy/renpy-8.3.6-sdk/renpy/ui.py", line 301, in interact
    rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
  File "/home/zloysnegovik/files/renpy/renpy-8.3.6-sdk/renpy/display/core.py", line 2218, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, pause=pause, pause_start=pause_start, pause_modal=pause_modal, **kwargs) # type: ignore
  File "/home/zloysnegovik/files/renpy/renpy-8.3.6-sdk/renpy/display/core.py", line 3289, in interact_core
    rv = root_widget.event(ev, x, y, 0)
  File "/home/zloysnegovik/files/renpy/renpy-8.3.6-sdk/renpy/display/layout.py", line 1297, in event
    rv = i.event(ev, x - xo, y - yo, cst)
  File "/home/zloysnegovik/files/renpy/renpy-8.3.6-sdk/renpy/display/layout.py", line 1297, in event
    rv = i.event(ev, x - xo, y - yo, cst)
  File "/home/zloysnegovik/files/renpy/renpy-8.3.6-sdk/renpy/display/layout.py", line 1297, in event
    rv = i.event(ev, x - xo, y - yo, cst)
  File "/home/zloysnegovik/files/renpy/renpy-8.3.6-sdk/renpy/display/screen.py", line 794, in event
    rv = self.child.event(ev, x, y, st)
  File "/home/zloysnegovik/files/renpy/renpy-8.3.6-sdk/renpy/display/layout.py", line 1297, in event
    rv = i.event(ev, x - xo, y - yo, cst)
  File "/home/zloysnegovik/files/renpy/renpy-8.3.6-sdk/renpy/display/layout.py", line 1297, in event
    rv = i.event(ev, x - xo, y - yo, cst)
  File "/home/zloysnegovik/files/renpy/renpy-8.3.6-sdk/renpy/display/behavior.py", line 1182, in event
    return handle_click(self.clicked)
  File "/home/zloysnegovik/files/renpy/renpy-8.3.6-sdk/renpy/display/behavior.py", line 1103, in handle_click
    rv = run(action)
  File "/home/zloysnegovik/files/renpy/renpy-8.3.6-sdk/renpy/display/behavior.py", line 401, in run
    return action(*args, **kwargs)
  File "renpy/common/00action_control.rpy", line 131, in __call__
    renpy.show_screen(self.screen, *self.args, **self.kwargs)
  File "/home/zloysnegovik/files/renpy/renpy-8.3.6-sdk/renpy/display/screen.py", line 1328, in show_screen
    raise Exception("Screen %s is not known.\n" % (name[0],))
Exception: Screen global_map is not known.


Linux-6.8.0-59-generic-x86_64-with-glibc2.35 x86_64
Ren'Py 8.3.6.25022803
TrueDragon 1.0
Thu May 29 00:27:59 2025
